### ISSUE TITLE
Project4

### ISSUE THREAD

**Issue by awziontka** [helpmoeny/CSE331#1]
Could someone push what they have for project 4 so far? I'm struggling on getting it to just read the file/construct the graph right now.

**Comment by helpmoeny** [comment]
I can't today unfortunately, working on 320. I'll try to get it to you tomorrow!

**Comment by awziontka** [comment]
Ok cool thanks man!

**Comment by helpmoeny** [comment]
So im still having issues with mine which really sucks, so while i'm working on that I don't want to leave you sitting in the dark so i'll post something that i found useful. https://github.com/wrightmhw/project5/blob/master/UnweightedGraph.cpp

**Comment by awziontka** [comment]
Ok sweet thanks! I've been doing 335 today, I'll take a look at it tomorrow and hopefully it'll clear some stuff up in the meantime.

**Comment by helpmoeny** [comment]
yeah i have been doing 320 for 3 hours and finished this weeks assignment, more time for 331 :+1: I just pushed 320 proj9. I didn't make any other headway with 331 that would even be useful so hopefully I can get more done tomorrow.

**Comment by awziontka** [comment]
Sounds good. I'm still on 335, but almost done. I'm hoping to get that and 320 done today/early tomorrow so I can get back to 331.

**Comment by nickbunton** [comment]
are you sure your divide for 320 works? i ran yours to see if it did and it wasn't working for me!
